### ISSUE TITLE
Add Loader 🌀

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/react-blog-github#14]
We need to add a loader when getting data from Github.

**Comment by mbaralle** [comment]
Hi @saadpasta ! Could you assign me to this one? ✋🏻

**Comment by saadpasta** [comment]
> Hi @saadpasta ! Could you assign me to this one? ✋🏻

Hi,@mbaralle you can take this. Go On.🌀

**Comment by jvm-odoo** [comment]
It can be done easily with GraphQL `useQuery` hook. see https://www.apollographql.com/docs/react/data/queries/
