### ISSUE TITLE
Add Dark Mode Option 🌙

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/react-blog-github#34]
Most applications nowadays have dark mode and it is commonly used in Blog for reader to read with more ease. I guess we should implement Dark Model in react-blog-github.

**Comment by AliTechGeek52** [comment]
@saadpasta I am working on this.

**Comment by saadpasta** [comment]
@AliTechGeek52 assigned to you

**Comment by saadpasta** [comment]
@AliTechGeek52 are you working on it.

**Comment by abhishekashyap** [comment]
Is this taken or under progress? If not, can I take this up?

**Comment by jvm-odoo** [comment]
@abhishekashyap Since we have no further news from AliTechGeek52, I guess you can take it.
