### ISSUE TITLE
Show blog from newest to lowest,

### ISSUE THREAD

**Issue by oHoVietTuan** [saadpasta/react-blog-github#44]
I clone and publish my blog based on your source code. https://tuanhv.dev

I don't know why my second and the third post did not show content detail, although the first one showed. 

Can you help me?

**Comment by tuanhv-0694** [comment]
Oh I found the bug, if title has `?` this can not show the content, due to the URL address

**Comment by tuanhv-0694** [comment]
in some ways the output in content detail is not same content  in issues github

**Comment by tuanhv-0694** [comment]
how can I change the way of sort in main page

**Comment by saadpasta** [comment]
I had a look at your blog. It is showing the perfect content.

**Comment by tuanhv-0694** [comment]
@saadpasta: thanks, your site was inspired to me a lot :D

**Comment by tuanhv-0694** [comment]
@saadpasta: I think posts should show from newest to lowest, and I reverse an array in containers Blog.js. Should I send this PR to contribute?

**Comment by saadpasta** [comment]
@tuanhv-0694 Yeah, that would be great.
