### ISSUE TITLE
Back buttom doesn't work

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/react-blog-github#47]
On clicking the back button on [Blog](https://saadpasta.github.io/react-blog-github/#/blog/React%20Blog%20Github%20(Test%20Issue)%201%20%20%F0%9F%94%A5/1) that doesn't work. It shows a loading sreen and then again comes to the same page. Please check it out.

**Comment by saadpasta** [comment]
working fine for me
did you try this while logged in

**Comment by naveen521kk** [comment]
![test](https://user-images.githubusercontent.com/49693820/80592369-f3bad500-8a3c-11ea-8bd0-321cbe0f1054.gif)
Here I have attached what just happened.
